env: "prod"
database_url: "postgres://postgres:123@auth_db:5432/auth?sslmode=disable"
token_ttl: 1h
grpc:
  port: 9000
  timeout: 10h
rest:
  port: 8080
rabbit_mq:
  url: amqp://guest:guest@rabbitmq:5672/
  queue_name: user_queue
